server:
  port: 8080

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    druid:
      # 初始连接数
      initial-size: 5
      # 最小连接池数量
      min-idle: 10
      # 最大连接池数量
      max-active: 30
      # 最大可以执行SQL语句的对象的个数
      max-open-prepared-statements: 200
      # 配置获取连接等待超时的时间，单位是毫秒
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      max-evictable-idle-time-millis: 900000
      # 配置检测连接是否有效
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      web-stat-filter:
        enabled: true
      stat-view-servlet:
        enabled: false
        # 设置白名单，不填则允许所有访问
        allow:
        url-pattern: /druid/*
        # 控制台管理用户名和密码
        login-username: admin
        login-password: admin***
  cache:
    redis:
      time-to-live: 24H
      key-prefix: "cy:cache:"

forest:
  interceptors: com.cy.config.ForestLogInterceptor
  log-handler: com.cy.config.ForestLogInterceptor

logging:
  config: classpath:log4j2-info.xml


---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    druid:
      template:
        enable: true
        url: jdbc:mysql://127.0.0.1:3306/information_schema?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false&rewriteBatchedStatements=true&&allowMultiQueries=true
        username: root
        password: 123.com
  redis:
    host: 127.0.0.1
    port: 6379
    database: 7